version: "3.8"

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: "tunnel --no-autoupdate"
    volumes:
      - ./cloudflared:/etc/cloudflared
    depends_on:
      - postgrest

  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - cloudflared

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    env_file:
      - .env
    ports:
      - "5050:80"
    links:
      - "postgres:pgsql-server"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - cloudflared

  portainer:
    image: portainer/portainer-ce
    container_name: potainer
    privileged: true
    ports:
      - "9001:9000"
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - cloudflared

networks:
  cloudflared:
    driver: bridge

volumes:
  postgres-data: {}
  pgadmin-data: {}
